version: '3.8'

services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - api-network
    volumes:
      - api-volume:/var/lib/postgresql/data

  cache:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
networks:
  api-network:
    driver: bridge

volumes:
  api-volume:
